export type GlossaryEntry = {
  canonical: string;
  definition: string;
  aliases?: string[];
  details?: string;
  examUse?: string;
  examples?: string[];
  related?: string[];
};

function entry(config: GlossaryEntry): GlossaryEntry {
  return config;
}

export const glossaryEntries: GlossaryEntry[] = [
  entry({
    canonical: "ACPO",
    aliases: ["ACPO Principles"],
    definition: "Association of Chief Police Officers guidance used as a foundational set of UK digital-forensics handling principles.",
    details: "In practical terms, ACPO is about preserving trust in evidence. The principles are designed to stop investigators from casually changing systems and then presenting those altered systems as if they were untouched originals. Even though modern practice and organizations have evolved, the ACPO principles remain a very common teaching framework because they express the core logic of defensible digital evidence handling clearly.",
    examUse: "If you see ACPO in an exam, do not just name the principles. Explain why they matter: preserving integrity, documenting actions, and ensuring someone competent can justify anything done to the original data.",
    related: ["Chain of custody", "write blocker", "PDE"],
  }),
  entry({
    canonical: "ADS",
    aliases: ["Alternate Data Streams"],
    definition: "Alternate Data Stream. An NTFS feature that allows additional named data streams to be attached to a file beyond the normal visible content.",
    details: "Most users think a file has one content area, but NTFS can attach multiple streams to a single filename. The default stream is what Explorer usually shows, while alternate streams can hide extra text, scripts, or payloads without changing the visible file size in obvious ways. This makes ADS useful both for legitimate metadata and for covert storage or malware hiding.",
    examUse: "In answers, mention both the technical fact and the forensic implication: ADS can conceal content and tools like dir /r or PowerShell stream inspection may reveal it.",
    examples: ["Zone.Identifier is a common ADS.", "A file like report.txt:secret may store hidden text."],
    related: ["NTFS", "Zone.Identifier", "MOTW"],
  }),
  entry({
    canonical: "AEAD",
    definition: "Authenticated Encryption with Associated Data. A class of modern encryption schemes, such as AES-GCM, that provide confidentiality and integrity together.",
    details: "Older protocol discussions often separate encryption from integrity, but AEAD modes combine those guarantees. In TLS discussions, AEAD is important because deprecated protocol versions often lack the stronger cipher and mode combinations expected in modern deployments.",
    examUse: "If AEAD appears in TLS questions, connect it to modern secure protocol use and why older versions such as TLS 1.0 or 1.1 are weaker by comparison.",
    related: ["TLS", "HSTS"],
  }),
  entry({
    canonical: "ASCII",
    definition: "A basic character encoding standard that maps letters, digits, and symbols to byte values.",
    details: "ASCII is foundational because many other encodings preserve ASCII values for the first 128 characters. It helps you reason about text in hex editors and low-level forensic work because simple English text often appears directly as readable bytes.",
    examUse: "Use ASCII when explaining why strings may be visible in binaries, memory, packet captures, or carved files.",
    related: ["UTF-8", "UTF-16"],
  }),
  entry({
    canonical: "ASLR",
    definition: "Address Space Layout Randomization. A memory-safety mitigation that randomizes memory layout to make exploitation harder.",
    details: "ASLR does not fix memory bugs; it makes them harder to exploit reliably by changing where important regions appear in memory. Attackers often need extra information leaks or bypass strategies if ASLR is in play. That is why memory disclosure bugs can be especially dangerous: they may reveal the layout needed to bypass other mitigations.",
    examUse: "When ASLR appears, explain it as a mitigation that increases exploit difficulty rather than a guarantee that a bug is harmless.",
    related: ["DEP", "Heartbleed", "MITM"],
  }),
  entry({
    canonical: "Atbash",
    definition: "A fixed substitution cipher that reverses the alphabet, mapping A to Z, B to Y, and so on.",
    details: "Unlike a general monoalphabetic substitution cipher, Atbash does not require a custom key because the mapping is always the same. That makes it easy to recognize once you notice the reverse alphabet pattern, and it is often used in teaching because it demonstrates substitution principles without key-management complexity.",
    examUse: "If asked about Atbash, stress that it is a specific substitution pattern, not a Caesar shift and not a random substitution key.",
    related: ["Caesar cipher", "monoalphabetic substitution cipher"],
  }),
  entry({
    canonical: "Autopsy",
    definition: "A digital-forensics platform that helps examine disk images, timelines, deleted files, and other artefacts.",
    details: "Autopsy is often used as a high-level analysis environment sitting on top of lower-level forensic concepts. It does not replace understanding file systems or artefacts; it gives you a structured interface for viewing them. In exams, tools like Autopsy matter because they illustrate workflow, but marks usually come from explaining what the tool is revealing, not just naming it.",
    examUse: "If you mention Autopsy, pair it with the artefact or task it supports: deleted-file recovery, registry review, timeline building, and so on.",
  }),
  entry({
    canonical: "BEAST",
    definition: "A TLS attack against older protocol and cipher configurations, often cited when discussing why TLS 1.0 became deprecated.",
    details: "BEAST is commonly used in teaching as a reason older TLS configurations should not be left enabled forever. You do not usually need to derive the cryptographic mathematics; you need to understand that old protocol support widens attack surface and weakens transport security policy.",
    examUse: "Use BEAST as supporting evidence for disabling TLS 1.0, not as an isolated trivia fact.",
    related: ["TLS", "HSTS"],
  }),
  entry({
    canonical: "BIOS",
    definition: "Basic Input/Output System. Firmware used to initialize hardware and start the boot process on older PCs.",
    details: "In forensic handling, BIOS data can reveal system time, detected storage devices, and boot order. That matters because boot order may show whether USB booting was possible, and BIOS time can help you assess clock drift before interpreting timestamps. On newer systems, UEFI provides similar information with a more modern firmware architecture.",
    examUse: "If BIOS inspection is requested, describe how you would enter setup, what you would record, and why those values matter for evidence interpretation.",
    related: ["UEFI", "UTC", "Chain of custody"],
  }),
  entry({
    canonical: "Blind XSS",
    definition: "A form of stored XSS where the attacker cannot see the payload execute directly and typically learns of success indirectly, often through a callback.",
    details: "Blind XSS often happens in admin panels, support systems, or logging backends where attacker-controlled input is displayed later to privileged users. The attacker submits a payload and waits for an external signal such as a webhook, network request, or other out-of-band interaction to confirm execution.",
    examUse: "Use Blind XSS to show that stored XSS is not limited to public comment systems. Back-office systems can be equally vulnerable and often have higher privilege impact.",
    related: ["XSS", "DOM", "Burp Suite"],
  }),
  entry({
    canonical: "Burp Suite",
    aliases: ["Burp"],
    definition: "A web-security testing platform commonly used as an intercepting proxy to inspect and modify HTTP requests and responses.",
    details: "Burp sits between the browser and the target application, allowing the tester to pause, inspect, change, replay, and compare web traffic. In beginner terms, it lets you stop trusting the browser interface and work directly with the underlying web requests. That makes it invaluable for login tampering, parameter manipulation, request replay, and vulnerability verification.",
    examUse: "If Burp appears in an answer, say what feature you would use: Proxy for interception, Repeater for manual replay and editing, and so on.",
    related: ["POST", "XSS", "Directory traversal"],
  }),
  entry({
    canonical: "CAINE",
    definition: "A Linux distribution designed for digital forensics and incident-response work.",
    details: "CAINE packages many forensic tools into one ready-to-use environment so the examiner does not need to install everything individually on a live exercise machine. In practical teaching, it reduces setup friction and helps maintain a known analysis environment.",
    examUse: "If a lab mentions CAINE, explain the workflow it supports rather than treating the distro name as the answer by itself.",
  }),
  entry({ canonical: "Caesar cipher", definition: "A substitution cipher that shifts each letter by a fixed number of places in the alphabet.", details: "It is one of the simplest classical ciphers and is useful in teaching because you can reason about both encryption and decryption mechanically. In the reverse-engineering practical, Caesar logic matters as a transformation step before recovering the real substitution mapping.", examUse: "Mention direction: a +3 shift and a -3 shift are different hypotheses until proven by readable output.", related: ["Atbash", "ROT13"] }),
  entry({ canonical: "Chain of custody", definition: "The documented record of who handled evidence, when they handled it, where it was, and what was done with it.", details: "Chain of custody is not just paperwork; it is how you preserve trust that evidence was not substituted, altered, or casually mishandled. Even excellent technical analysis can be weakened if continuity records are incomplete or unclear.", examUse: "In exams, pair chain of custody with concrete fields: exhibit ID, date/time, handler, transfer reason, and storage condition.", related: ["ACPO", "write blocker", "PDE"] }),
  entry({ canonical: "CMDB", definition: "Configuration Management Database. A structured inventory of systems, software, versions, and relationships used in operations and security management.", details: "A CMDB matters because you cannot patch, assess, or prioritize what you cannot reliably identify. In reporting and patch-management questions, CMDB discussions show that vulnerability handling is a process problem as much as a technical one.", examUse: "Use CMDB when explaining asset inventory, remediation ownership, and why decade-old vulnerabilities should not survive unnoticed.", related: ["SLA", "CVE", "CVSS"] }),
  entry({ canonical: "CSP", definition: "Content Security Policy. A browser security header that restricts where scripts and other active content may be loaded from.", details: "CSP is often described as a defence-in-depth control for XSS. It does not replace output encoding, but it can reduce the damage of some XSS payloads by blocking inline execution or untrusted script sources. A poor CSP, however, can be almost useless if it still allows dangerous patterns like unsafe-inline.", examUse: "In exam answers, say clearly that CSP is supportive rather than primary; output encoding remains the main defence.", related: ["XSS", "HttpOnly", "output encoding"] }),
  entry({ canonical: "CSRF", definition: "Cross-Site Request Forgery. An attack that tricks a user’s browser into making an unwanted authenticated request to a target site.", details: "CSRF abuses the fact that browsers automatically attach cookies or other ambient credentials when visiting a site. Unlike XSS, CSRF does not require running attacker JavaScript inside the victim origin; it relies on browser behavior and weak anti-forgery protections.", examUse: "When comparing XSS and CSRF, note that XSS can often read or manipulate page context directly, while CSRF is about tricking the browser into sending an unwanted state-changing request.", related: ["XSS", "HttpOnly", "POST"] }),
  entry({ canonical: "CVE", definition: "Common Vulnerabilities and Exposures. A standard identifier used to name publicly known security vulnerabilities.", details: "A CVE number gives a shared reference so researchers, vendors, scanners, and defenders can all discuss the same vulnerability consistently. It names the issue; it does not by itself explain severity, exploitability, or environmental risk.", examUse: "If you cite a CVE, pair it with what the vulnerability is, why it matters, and if relevant how it was verified.", related: ["CVSS", "OpenSSL", "Heartbleed"] }),
  entry({ canonical: "CVSS", definition: "Common Vulnerability Scoring System. A framework for expressing the technical severity characteristics of a vulnerability.", details: "CVSS gives a structured way to talk about exploitability and impact using metrics such as attack vector, privileges required, user interaction, and confidentiality impact. It is powerful for standardization but should not be mistaken for a complete business-risk model. Context, active exploitation, asset criticality, regulation, and operational reality can all make a vulnerability more or less urgent than the base score suggests.", examUse: "In answers, write both the score and what the vector means. If asked why a real-world rating is higher than the base score, explain the environmental or operational context.", related: ["CVE", "SLA", "PoC"] }),
  entry({ canonical: "DCT", definition: "Discrete Cosine Transform. A mathematical transform used in formats like JPEG, where steganographic data can be hidden in frequency-domain coefficients.", details: "You do not need to derive DCT mathematics for EHAC use. What matters is understanding that some formats store image information in a transformed form, and hiding data there can survive compression better than simple least-significant-bit tricks.", examUse: "Use DCT to contrast JPEG-friendly steganography with fragile pixel-space LSB techniques.", related: ["LSB", "Steganalysis"] }),
  entry({ canonical: "dd", definition: "A command-line utility commonly used for low-level copying, including bit-for-bit acquisition of storage media in forensic workflows.", details: "In forensic imaging, dd is valuable because it copies raw blocks rather than only logical files. That means unallocated space and other low-level regions can be preserved. The downside is that you must use it carefully, because a wrong source or destination argument can overwrite the wrong thing.", examUse: "If you mention dd, also mention verification with hashing and the importance of identifying the correct device first.", related: ["write blocker", "sha256sum", "Sleuth Kit"] }),
  entry({ canonical: "DEP", definition: "Data Execution Prevention. A mitigation that prevents execution from memory regions intended only for data.", details: "DEP is another example of a mitigation that changes exploitability but does not remove the underlying vulnerability. Attackers often need a bypass, a memory-disclosure helper, or a different exploitation strategy if DEP is present.", examUse: "Use DEP alongside ASLR when describing exploit mitigations and why some vulnerabilities need more than one condition to become weaponizable.", related: ["ASLR", "Heartbleed"] }),
  entry({ canonical: "DOM", aliases: ["DOM-based XSS", "DOM XSS"], definition: "Document Object Model. The browser’s in-memory representation of a web page that JavaScript can read and modify.", details: "The DOM is what client-side code actually manipulates when it changes a page after load. DOM-based XSS happens when JavaScript takes attacker-controlled data such as location.hash or a query parameter and injects it into dangerous sinks like innerHTML without safe handling. The server may never reflect the payload in the response at all.", examUse: "If the question is about DOM XSS, focus on client-side data flow and unsafe DOM sinks rather than server-side reflection.", related: ["innerHTML", "XSS", "Same-Origin Policy"] }),
  entry({ canonical: "Event ID", definition: "A numeric identifier in Windows Event Logs that indicates a particular type of recorded activity or event.", details: "An Event ID is useful because it gives a stable handle for filtering recurring system activity, such as successful logons or time changes. On its own it is not enough; you still need the surrounding fields such as timestamp, user context, and machine name.", examUse: "In exam answers, cite the important Event IDs but also explain what they prove and what they do not prove.", related: ["SIEM", "RDP", "NTP"] }),
  entry({ canonical: "EXIF", definition: "Exchangeable Image File Format metadata commonly stored in image files, often containing timestamps, device details, and other attributes.", details: "EXIF is useful in both steganography and forensics because it can reveal how a file was created, edited, or processed. It can also mislead if copied, stripped, or rewritten, so it should be corroborated rather than trusted blindly.", examUse: "Mention EXIF when discussing image metadata, tool workflows, or inconsistencies between claimed and actual file origin.", related: ["Steganalysis"] }),
  entry({ canonical: "FAT", definition: "File Allocation Table. An older file system commonly found on removable media; unlike NTFS, it stores timestamps in local time.", details: "FAT matters because it is simpler and often leaves fewer forensic artefacts than NTFS, but it also creates interpretation traps. The biggest one is time handling: because FAT stores local time, the examiner must know the machine’s timezone and daylight-saving context before drawing conclusions.", examUse: "When FAT appears, almost always mention local time and the risk of timezone misinterpretation.", related: ["NTFS", "UTC", "FILETIME"] }),
  entry({ canonical: "FILETIME", definition: "A Windows timestamp format that counts 100-nanosecond intervals since 1601-01-01 UTC.", details: "FILETIME is common in Windows internals, registry values, and NTFS-related analysis. The important part for exams is identifying that a large little-endian 64-bit value may be a FILETIME and that it uses UTC, not local time.", examUse: "If converting FILETIME, show the recognition step first. Identifying the format is part of the answer.", related: ["UTC", "NTFS", "Registry"] }),
  entry({ canonical: "FTK Imager", definition: "A forensic imaging and preview tool often used to acquire and inspect evidence drives and files.", details: "FTK Imager is a practical tool example for acquisition and preview, especially in Windows-oriented teaching. Like other forensic tools, its value in exams usually comes from the workflow it supports rather than the brand name itself.", examUse: "If you cite FTK Imager, say what it is doing: creating a forensic image, previewing evidence, or exporting selected items.", related: ["Autopsy", "dd", "write blocker"] }),
  entry({ canonical: "GUID", definition: "Globally Unique Identifier. A 128-bit identifier commonly used in Windows for objects, device classes, and software references.", details: "GUIDs are often confusing because they look opaque, but in forensic work they can be decoded into meaningful categories such as device classes or known system objects. They are therefore often stepping stones from raw registry data to human explanation.", examUse: "When asked about GUIDs, explain their role as identifiers and, if relevant, how they help locate USB or system artefacts.", related: ["SID", "Registry", "USB Device Forensics"] }),
  entry({ canonical: "HSTS", definition: "HTTP Strict Transport Security. A response header that tells browsers to use HTTPS only for a domain, reducing SSL-stripping risk.", details: "HSTS helps defend users who might otherwise be downgraded to plain HTTP or tricked during the first insecure request. The includeSubDomains and preload options matter because weak or incomplete deployment leaves gaps across related hosts.", examUse: "If discussing HSTS, mention that it strengthens transport policy but must be configured consistently to be fully useful.", related: ["TLS", "HTTPS", "SSL stripping"] }),
  entry({ canonical: "HttpOnly", definition: "A cookie flag that prevents JavaScript from reading the cookie via document.cookie.", details: "HttpOnly is a valuable XSS mitigation for session theft, but it does not stop all XSS impact. An attacker may still be able to act as the user through authenticated requests even if the cookie value itself cannot be read directly.", examUse: "In XSS answers, never present HttpOnly as a complete fix. It specifically helps with client-side cookie theft.", related: ["XSS", "CSP", "CSRF"] }),
  entry({ canonical: "HTTPS", definition: "HTTP layered over TLS, providing encrypted and authenticated web communication.", details: "HTTPS aims to provide confidentiality, integrity, and server authentication for web traffic. It is not just 'HTTP but secure'; its real security quality depends on protocol versions, certificate handling, and secure configuration.", examUse: "If HTTPS is discussed in vulnerability questions, connect it to TLS versions, HSTS, certificate trust, and the difference between having encryption and configuring it well.", related: ["TLS", "HSTS", "OpenSSL"] }),
  entry({ canonical: "Hive", aliases: ["Hives"], definition: "A registry storage file on disk, such as SAM, SYSTEM, SOFTWARE, or NTUSER.DAT, that contributes to the live Windows Registry.", details: "A hive is the offline storage unit; the live Windows Registry is built from several hives mounted together. This distinction matters because offline analysis lets investigators inspect registry content from an image without booting the suspect system.", examUse: "If asked about registry hives, explain both what they are and why offline hive analysis is forensically useful.", related: ["Registry", "SAM", "NTUSER.DAT"] }),
  entry({ canonical: "innerHTML", definition: "A DOM property that parses assigned strings as HTML. It is convenient but dangerous when fed untrusted data.", details: "innerHTML is one of the classic dangerous sinks in DOM-based XSS because it treats a string as markup rather than plain text. If attacker-controlled input reaches it without safe processing, tags and scripts can become executable structure instead of harmless content.", examUse: "If a question asks for a dangerous DOM API, innerHTML is one of the clearest examples.", related: ["DOM", "XSS", "output encoding"] }),
  entry({ canonical: "JWT", definition: "JSON Web Token. A compact token format often used to carry authentication or session claims in web systems.", details: "A JWT is commonly used as a bearer token: possession can be enough for access, so leakage can be extremely serious. In the PizzaPineapple case study, recovered JWTs show how a read-only memory disclosure can still become full authenticated compromise.", examUse: "If JWT appears in a report or attack chain answer, explain that stealing the token may be enough to impersonate the user without the password.", related: ["Heartbleed", "HttpOnly", "PoC"] }),
  entry({ canonical: "Kerberos", definition: "A network authentication protocol used heavily in Windows domains, often appearing in domain logon event flows.", details: "Kerberos separates identity proof and service access through tickets rather than repeatedly sending passwords. In Windows logon analysis, this matters because some events occur on the domain controller and others on the workstation, so the examiner may need both viewpoints.", examUse: "If you mention Kerberos, connect it to domain logon workflows and event IDs like 4768.", related: ["RDP", "Event ID", "SID"] }),
  entry({ canonical: "LD_PRELOAD", definition: "An environment variable that tells the dynamic linker to load specified shared libraries before others, allowing symbol override attacks or debugging tricks.", details: "LD_PRELOAD works because dynamically linked programs resolve imported symbols at runtime. By forcing a chosen library to load first, you can override functions such as puts and change program behavior without modifying the original binary file itself.", examUse: "In reverse-engineering answers, explain both the mechanism and why it only helps when symbols are externally resolved.", related: ["Atbash", "ASLR", "DEP"] }),
  entry({ canonical: "LSB", definition: "Least Significant Bit. The lowest-order bit in a byte; often used in simple image steganography because changing it has minimal visible effect.", details: "In a color channel byte, changing the least significant bit usually alters the value by only one, which humans typically cannot see. That makes LSB steganography easy to implement but also fragile and often detectable with statistical analysis.", examUse: "When explaining LSB, mention both invisibility and fragility.", related: ["Steganalysis", "DCT"] }),
  entry({ canonical: "MACB", definition: "A mnemonic for four NTFS timestamps: Modified, Accessed, Changed, and Born (Created).", details: "MACB is useful because it forces you to think about different kinds of time evidence instead of just one 'file date'. The key distinction students often miss is that Changed refers to metadata change, not necessarily content modification.", examUse: "If asked about timestomping or suspicious dates, contrast STANDARD_INFORMATION and FILE_NAME timestamps as well as Modified versus Changed.", related: ["NTFS", "timestomping", "FILETIME"] }),
  entry({ canonical: "Metasploit", definition: "A framework for exploitation, payload delivery, and security testing, often used to validate known vulnerabilities.", details: "Metasploit is useful because it turns vulnerability validation into a repeatable workflow with modules, payload handling, and session management. In teaching, it is often used not because every real attack uses it, but because it standardizes proof-of-concept demonstration.", examUse: "If you mention Metasploit in a report answer, explain whether it was used for validation, not just name-dropping the tool.", related: ["PoC", "Heartbleed", "Burp Suite"] }),
  entry({ canonical: "MFT", definition: "Master File Table. NTFS’s central record structure containing metadata about files and directories.", details: "The MFT is one of the most important NTFS artefacts because it stores file records, timestamps, names, attributes, and sometimes even small file content. Deleted files may leave valuable traces here even after they disappear from normal directory listings.", examUse: "If a deleted-file or NTFS question appears, MFT should be one of the first artefacts you discuss.", related: ["NTFS", "MACB", "resident data"] }),
  entry({ canonical: "MITM", definition: "Man-in-the-middle. An attack in which an adversary positions themselves between communicating parties to intercept or alter traffic.", details: "MITM is a position, not one single technique. The attacker may relay, read, modify, downgrade, or spoof traffic between parties who believe they are communicating directly.", examUse: "Use MITM when explaining protocol downgrade risks, weak transport policy, or trust failures around certificates and encryption.", related: ["TLS", "HTTPS", "HSTS"] }),
  entry({ canonical: "MOTW", definition: "Mark of the Web. Windows trust metadata, usually implemented as a Zone.Identifier ADS, indicating that a file came from an untrusted zone.", details: "MOTW is operationally important because Windows and Office use it to trigger extra warnings or restrictions on downloaded content. Forensics cares because it can show that a file came from the Internet even if the user later claims it was purely local.", examUse: "If MOTW appears, connect it to Zone.Identifier and to origin evidence for suspicious files.", related: ["Zone.Identifier", "ADS", "NTFS"] }),
  entry({ canonical: "MRU", definition: "Most Recently Used. A common artefact category that records recently opened files, folders, or choices.", details: "MRU artefacts do not usually prove file content or who typed at the keyboard, but they are very useful timeline clues. They often show that a user or account interacted with a file, dialog, or path around a certain time.", examUse: "Use MRU data as supportive evidence, especially when building a sequence together with UserAssist, RecentDocs, or link files.", related: ["UserAssist", "Registry", "RecentDocs"] }),
  entry({ canonical: "NSE", definition: "Nmap Scripting Engine. A scripting system inside Nmap used for checks such as ssl-heartbleed.", details: "NSE extends Nmap beyond raw port discovery into scripted vulnerability checks, service interrogation, and protocol behavior testing. That makes it useful for verification as well as reconnaissance.", examUse: "If you cite NSE, explain the specific script and what its output demonstrated.", related: ["Nmap", "Heartbleed", "OSINT"] }),
  entry({ canonical: "NTFS", definition: "New Technology File System. The standard modern Windows file system, rich in metadata useful to forensic analysis.", details: "NTFS is central to Windows forensics because it stores names, timestamps, allocation state, and structured attributes in ways that often outlive casual user expectations. Compared with FAT, it provides more artefacts but also more conceptual complexity.", examUse: "If NTFS appears, mention MFT, UTC timestamps, and rich metadata as key distinguishing features.", related: ["MFT", "MACB", "ADS", "resident data"] }),
  entry({ canonical: "NTP", definition: "Network Time Protocol. A protocol used to synchronize clocks across systems and networks.", details: "NTP matters in forensics because a timeline is only as good as the clock it depends on. Event logs around NTP sync or manual time changes can help the examiner decide whether recorded times are trustworthy.", examUse: "When discussing time reliability, mention both sync events and manual clock-change events.", related: ["UTC", "Event ID", "FILETIME"] }),
  entry({ canonical: "Open File Table", aliases: ["OFT"], definition: "The operating system’s kernel-side structure that stores state for open files, such as offset and access mode.", details: "Students often picture open files as the process 'holding the file itself', but the process actually holds only descriptors that point to kernel-managed open-file state. That is why multiple descriptors or processes can sometimes refer to related file state while maintaining different semantics depending on duplication and opening behavior.", examUse: "For exam answers, distinguish the user-visible descriptor integer from the kernel-maintained structure that tracks the open file state.", related: ["dd", "strace"] }),
  entry({ canonical: "OpenSSL", definition: "A widely used cryptographic library implementing TLS and related features; Heartbleed was an implementation flaw in OpenSSL.", details: "OpenSSL is infrastructure software: many applications rely on it rather than implementing TLS themselves. That is why one library bug can have extremely wide consequences across web servers, VPNs, mail systems, and appliances.", examUse: "If OpenSSL appears in a case study, make clear whether the issue is with the protocol concept or the library implementation.", related: ["TLS", "Heartbleed", "HTTPS"] }),
  entry({ canonical: "OpenVAS", definition: "A vulnerability scanner used to identify known weaknesses across hosts and services.", details: "OpenVAS is useful for breadth, but like other scanners it does not automatically tell you whether a finding is exploitable, important in context, or a false positive. That is why pentest methodology separates scanning from exploitation and validation.", examUse: "If you mention OpenVAS, say what phase it supports: discovery, not final proof of impact.", related: ["PTES", "PoC", "Metasploit"] }),
  entry({ canonical: "OSINT", definition: "Open-Source Intelligence. Information gathered from public sources such as DNS records, certificate logs, search engines, and archived content.", details: "OSINT is valuable because it can reveal attack surface before any direct contact with the target. Subdomains, historical content, employee names, server banners, and public certificates can all reduce the uncertainty of later testing.", examUse: "If an exam asks what to do first in a legal pentest, OSINT is often one of the safest and most defensible starting points.", related: ["Shodan", "PTES", "Burp Suite"] }),
  entry({ canonical: "output encoding", definition: "Escaping or encoding untrusted data so that it is treated as data, not executable markup or code, in a specific output context.", details: "Output encoding is the main XSS defence because the danger appears when untrusted input is rendered in a browser context. The exact encoding must match the sink: HTML body, attribute, JavaScript string, URL, and CSS all have different rules.", examUse: "If asked for the primary XSS defence, say output encoding first, then explain why context matters.", related: ["XSS", "CSP", "innerHTML"] }),
  entry({ canonical: "PDE", definition: "Potential Digital Evidence. A source that may contain evidence, but whose evidential significance has not yet been fully established.", details: "PDE is a useful discipline word because it reminds you not to overstate what you have found too early. A machine, USB device, or log may contain evidence, but until analysed it is more accurate to describe it as a potential evidence source.", examUse: "Use PDE language in scene-handling answers to sound precise and forensically disciplined.", related: ["Chain of custody", "ACPO"] }),
  entry({ canonical: "Perfect Forward Secrecy", aliases: ["PFS"], definition: "A TLS property where compromise of long-term private keys does not automatically decrypt past captured sessions.", details: "PFS matters because without it, stealing a server private key may allow retrospective decryption of previously captured encrypted traffic. That is why memory-leak bugs affecting key material can be even more damaging on systems without forward secrecy.", examUse: "If PFS appears in Heartbleed-style questions, connect it to retrospective decryption risk.", related: ["TLS", "OpenSSL", "Heartbleed"] }),
  entry({ canonical: "PoC", definition: "Proof of Concept. A demonstration that a vulnerability is real and exploitable or that a technique works as claimed.", details: "A PoC is not the same as full weaponization. In professional work, it usually means enough evidence to prove reality and impact without causing unnecessary damage.", examUse: "If you say you produced a PoC, explain what exactly it demonstrated: execution, data exposure, privilege gain, or some other impact.", related: ["Metasploit", "Burp Suite", "CVSS"] }),
  entry({ canonical: "POST", definition: "An HTTP method commonly used to submit form data or create server-side state.", details: "POST changes how data is carried in the request, but it does not make the traffic confidential. Without HTTPS, POST bodies can still be captured and read in transit.", examUse: "This is a classic trap: do not claim POST is secure just because credentials are not in the URL.", related: ["HTTPS", "Wireshark", "Burp Suite"] }),
  entry({ canonical: "PTES", definition: "Penetration Testing Execution Standard. A common framework describing pentest phases such as planning, reconnaissance, exploitation, and reporting.", details: "PTES is useful because it makes pentesting methodical rather than ad hoc. It gives a structure for scoping, evidence generation, controlled validation, and reporting that clients can understand and auditors can review.", examUse: "If asked to describe pentest methodology, PTES gives you a clean phase-based framework.", related: ["OSINT", "OpenVAS", "Metasploit"] }),
  entry({ canonical: "RDP", definition: "Remote Desktop Protocol. A Microsoft protocol used for remote interactive logon, often reflected by Windows logon type 10 events.", details: "RDP matters in investigations because it is a common legitimate admin mechanism but also a common intrusion path. A logon type 10 event often shifts attention toward remote interactive access and source-system correlation.", examUse: "Do not treat all RDP use as malicious; explain why it needs context.", related: ["Event ID", "Kerberos", "SID"] }),
  entry({ canonical: "RegRipper", definition: "A registry-analysis tool that extracts common forensic artefacts from Windows hive files using plugins.", details: "RegRipper is useful because it turns hive analysis into focused artefact extraction instead of forcing you to browse every key manually. It is especially good in labs for demonstrating that you know which artefact families matter.", examUse: "Name the plugin purpose if possible, such as recentdocs or timezone, rather than only naming the tool.", related: ["Registry", "Hive", "UserAssist"] }),
  entry({ canonical: "resident data", definition: "Small NTFS file content stored directly inside the MFT record rather than in separate external clusters.", details: "Resident data matters because it changes how you think about recovery and slack space. If content is inside the MFT record itself, some forensic behaviors differ from larger files that occupy separate clusters on disk.", examUse: "Use resident data to show that not every file behaves the same way at the storage level.", related: ["MFT", "NTFS", "slack space"] }),
  entry({ canonical: "ROT13", definition: "A simple letter substitution that rotates letters by 13 places; Windows UserAssist uses it as an obfuscation method for program names.", details: "ROT13 is not encryption in any serious sense; it is trivial reversible obfuscation. In forensic work it matters because artefacts may look unfamiliar until you realize the names are transformed in this predictable way.", examUse: "If an artefact search is missing obvious program names, mentioning ROT13 can be the mark-winning insight.", related: ["UserAssist", "Caesar cipher"] }),
  entry({ canonical: "RSA", definition: "A public-key cryptographic system widely used for key exchange, signatures, and certificates.", details: "For EHAC purposes, RSA often matters because private-key compromise undermines identity and decryption trust. If an RSA private key leaks, attackers may impersonate the service and sometimes decrypt captured traffic depending on deployment choices.", examUse: "In Heartbleed-style questions, explain why partial or full RSA key recovery is so serious.", related: ["OpenSSL", "TLS", "Perfect Forward Secrecy"] }),
  entry({ canonical: "SAM", definition: "Security Account Manager. In Windows, a registry-related data source involved in local account information and authentication artefacts.", details: "SAM is important because local user-account information lives here, making it useful for understanding accounts present on a system. It forms part of the broader registry and authentication picture rather than standing alone.", examUse: "Mention SAM when discussing local accounts, credential validation context, or registry hive locations.", related: ["Hive", "SID", "Kerberos"] }),
  entry({ canonical: "Same-Origin Policy", aliases: ["SOP"], definition: "A browser security rule that isolates one web origin from another unless explicitly allowed.", details: "The Same-Origin Policy is what normally stops one site from reading another site's sensitive data in the browser. XSS is powerful because the malicious code is treated as belonging to the trusted origin itself, so SOP ends up helping the attacker instead of the defender.", examUse: "When explaining XSS impact, connect it to SOP and origin trust.", related: ["XSS", "DOM", "HttpOnly"] }),
  entry({ canonical: "Shodan", definition: "A search engine for Internet-exposed services and devices, often used in OSINT and reconnaissance.", details: "Shodan is useful because it lets testers search public exposure and historical banners without touching the target directly. That makes it a classic OSINT source for version clues, internet-facing service discovery, and exposed infrastructure patterns.", examUse: "If cited in methodology, place it in passive reconnaissance rather than active scanning.", related: ["OSINT", "PTES"] }),
  entry({ canonical: "SID", definition: "Security Identifier. A Windows identifier that uniquely represents a user or security principal.", details: "SIDs matter because many forensic artefacts store the SID rather than the friendly username. To make sense of the evidence, the examiner often has to map a SID back to a profile or account using registry paths such as ProfileList.", examUse: "Whenever a SID appears, explain what it identifies and how you would map it to a user.", related: ["GUID", "Registry", "Recycle Bin"] }),
  entry({ canonical: "SIEM", definition: "Security Information and Event Management. A platform for centralizing, searching, and correlating logs and security telemetry.", details: "A SIEM matters because local logs may be overwritten, fragmented, or incomplete, while centralized collection can preserve and correlate data over longer periods. In many real investigations, the SIEM is where the most complete timeline actually lives.", examUse: "Use SIEM to explain why local absence of logs is not always the end of the story.", related: ["Event ID", "Chain of custody"] }),
  entry({ canonical: "SLA", definition: "Service Level Agreement. In security contexts, often used to define required remediation timelines by severity.", details: "A security SLA converts severity into action expectations. It helps organizations move from vague concern to accountable deadlines such as critical within 24 hours or high within 7 days.", examUse: "If reporting asks for remediation planning, SLAs show operational maturity rather than just technical knowledge.", related: ["CVSS", "CMDB", "CVE"] }),
  entry({ canonical: "slack space", definition: "Unused bytes at the end of the last allocated cluster for a file; may contain remnants of previous data.", details: "Slack space exists because allocation units are larger than many file endings, leaving unused bytes at the tail of the final cluster. Those bytes can preserve remnants from prior content or be used deliberately as a hiding place.", examUse: "If asked why slack space matters, mention both accidental remnants and intentional hiding potential.", related: ["resident data", "MFT", "NTFS"] }),
  entry({ canonical: "Sleuth Kit", definition: "A suite of digital-forensics command-line tools for analysing file systems, timelines, metadata, and deleted content.", details: "Sleuth Kit is valuable because it exposes low-level artefacts directly: file listings, metadata, timelines, and content extraction. It is especially good for showing that you understand how evidence is structured beneath GUI abstractions.", examUse: "If you name a Sleuth Kit command, say what it extracts or proves, such as inode metadata or a bodyfile timeline.", related: ["Autopsy", "dd", "MFT"] }),
  entry({ canonical: "SOP", definition: "Standard Operating Procedure. A predefined, step-by-step process used to improve consistency and defensibility.", details: "SOPs matter because incident response under pressure is error-prone. A tested procedure reduces guesswork, makes actions reproducible, and helps defend decisions later in audits, investigations, or court settings.", examUse: "In planning questions, SOPs are strong evidence that an organization is forensically prepared before the incident occurs.", related: ["ACPO", "Chain of custody", "PTES"] }),
  entry({ canonical: "Steganalysis", definition: "The process of detecting or analysing hidden data inside a carrier such as an image, audio file, or other artefact.", details: "Steganalysis is usually about building confidence that something is unusual rather than instantly recovering the hidden message. Metadata, statistical patterns, bit-plane anomalies, and size inconsistencies all contribute to that confidence.", examUse: "When writing about steganalysis, mention workflow: identify, inspect metadata, search strings, look for embedded files, then apply format-specific analysis.", related: ["LSB", "DCT", "EXIF"] }),
  entry({ canonical: "testssl.sh", definition: "A command-line TLS analysis script used to test supported protocols, ciphers, and known TLS-related weaknesses.", details: "testssl.sh is practical because it quickly answers configuration questions that matter in pentests: protocol support, HSTS, Heartbleed checks, weak ciphers, and more. It complements version banners by testing observable behavior.", examUse: "If cited in a finding, say what aspect it verified: protocol support, Heartbleed exposure, HSTS, or cipher weakness.", related: ["TLS", "OpenSSL", "HSTS"] }),
  entry({ canonical: "timestomping", definition: "Deliberate manipulation of timestamps to mislead investigators about when a file was created, changed, or accessed.", details: "Timestomping is valuable to attackers because investigators often rely heavily on timelines. In NTFS, comparing STANDARD_INFORMATION and FILE_NAME timestamps is one way to spot suspicious manipulation.", examUse: "If you see inconsistent timestamp sets, explain why they may indicate timestomping but also consider benign causes like copying.", related: ["MACB", "NTFS", "FILETIME"] }),
  entry({ canonical: "TLS", aliases: ["SSL/TLS"], definition: "Transport Layer Security. The modern protocol suite used to secure network traffic such as HTTPS.", details: "TLS aims to provide confidentiality, integrity, and authenticated communication over untrusted networks. But having TLS is not enough by itself: version choice, ciphers, certificate handling, HSTS, and library quality all affect real security.", examUse: "If TLS is mentioned, ask: which version, what configuration, what evidence, and what business impact if it fails?", related: ["HTTPS", "HSTS", "OpenSSL"] }),
  entry({ canonical: "TRIM", definition: "An SSD feature that tells the drive which blocks are no longer in use, potentially causing rapid destruction of deleted data remnants.", details: "TRIM changes deleted-file expectations because the SSD may aggressively clean blocks after the operating system marks them free. That means classic 'deleted but still there' assumptions from spinning disks often fail on SSDs.", examUse: "If an answer discusses deleted SSD data, mention TRIM as a major recovery limitation.", related: ["NTFS", "slack space", "VSS"] }),
  entry({ canonical: "UEFI", definition: "Unified Extensible Firmware Interface. The modern replacement for classic BIOS firmware on many systems.", details: "UEFI plays a similar forensic role to BIOS for many exam questions: it can expose boot order, detected devices, firmware version, and clock settings. In practical handling, the important point is still what you record and why, not the branding of the firmware interface.", examUse: "If the question says BIOS/EFI, answer in a way that covers both and focuses on inspection goals.", related: ["BIOS", "UTC"] }),
  entry({ canonical: "UTC", definition: "Coordinated Universal Time. A standard time reference used to avoid ambiguity across time zones.", details: "UTC is central to forensics because it gives a common reference point across systems, regions, and daylight-saving changes. Misunderstanding whether a source uses UTC or local time is one of the easiest ways to corrupt a timeline.", examUse: "Whenever timestamps are discussed, explicitly say whether the source stores UTC or local time.", related: ["FILETIME", "NTFS", "FAT"] }),
  entry({ canonical: "UserAssist", definition: "A Windows Registry artefact that records evidence of program execution, often with names ROT13-obfuscated.", details: "UserAssist is valuable because it can show that a user account executed or interacted with a program. It is not perfect proof of human identity, but it is a strong timeline and activity artefact when combined with other sources.", examUse: "If asked how to find evidence of program execution in the registry, UserAssist is one of the first artefacts to mention.", related: ["ROT13", "MRU", "Registry"] }),
  entry({ canonical: "VSS", aliases: ["Volume Shadow Copies"], definition: "Volume Shadow Copy Service. A Windows snapshot mechanism that can preserve older file versions.", details: "VSS matters because it can preserve data that has since been altered or deleted from the live file system. It is also operationally useful to attackers and defenders alike, which is why ransomware often tries to delete shadow copies first.", examUse: "Use VSS when explaining how older versions may survive or why their absence can itself be suspicious.", related: ["TRIM", "NTFS", "Recycle Bin"] }),
  entry({ canonical: "write blocker", aliases: ["write blocker", "write blockers"], definition: "A hardware or software mechanism that prevents writes to evidence media during acquisition or examination.", details: "A write blocker helps satisfy the principle that the original evidence should not be changed by the examiner. Hardware write blockers are generally preferred because they provide stronger assurance than software-only approaches.", examUse: "If acquisition is discussed, write blockers are one of the easiest ways to show ACPO-aware handling.", related: ["dd", "ACPO", "Chain of custody"] }),
  entry({ canonical: "XSS", aliases: ["Cross-Site Scripting"], definition: "Cross-Site Scripting. A vulnerability where attacker-controlled data is executed by a victim’s browser in the context of a trusted site.", details: "The key idea is browser trust, not just script injection. The application causes the browser to treat attacker content as if it belonged to the legitimate site, which means origin-based protections may actually help the attacker once execution begins. XSS can be reflected, stored, blind, or DOM-driven depending on where the data is introduced and executed.", examUse: "If you define XSS in an exam, mention the victim browser, the trusted origin, and why output encoding is the main defence.", related: ["CSP", "HttpOnly", "Same-Origin Policy"] }),
  entry({ canonical: "Zone.Identifier", definition: "A Windows ADS used to record a file’s source trust zone, often implementing the Mark of the Web.", details: "Zone.Identifier commonly stores fields such as ZoneId, ReferrerUrl, and HostUrl, making it useful for establishing where a downloaded file came from. It is a simple artefact with surprisingly high evidential value when present.", examUse: "If a question asks how to show that a file came from the Internet, Zone.Identifier is one of the strongest concise answers.", related: ["ADS", "MOTW", "NTFS"] }),
];

export type GlossaryMatch = {
  alias: string;
  key: string;
  definition: string;
  canonical: string;
};

export function getGlossaryEntry(term: string) {
  const lowered = term.toLowerCase();
  return glossaryEntries.find((entry) => entry.canonical.toLowerCase() === lowered || (entry.aliases ?? []).some((alias) => alias.toLowerCase() === lowered));
}

export const glossaryMatches: GlossaryMatch[] = glossaryEntries
  .flatMap((entry) => [entry.canonical, ...(entry.aliases ?? [])].map((alias) => ({
    alias,
    key: alias.toLowerCase(),
    definition: entry.definition,
    canonical: entry.canonical,
  })))
  .sort((a, b) => b.alias.length - a.alias.length);
